Repository WildAid/o-fish-web, pull requests merged in 2020-07, with the labels that each got.

#54 #52 issue fix
  src/components/boardings/boarding-edit/basic-info/basic-info.section.js
  src/components/boardings/boarding-edit/boarding-edit.component.js
  src/components/boardings/boarding-edit/boardings-edit.css
  src/components/boardings/boarding-edit/risks/risks.section.js
Labels: bug

#59 Added view mode for Agency page + minor bugs
  src/components/agencies/agencies.component.js
  src/components/agencies/view-agency/view-agency.component.js
  src/components/boardings/boardings.component.js
  src/components/partials/text-viewer/text-viewer.js
  src/components/search-results/boardings/boardings.component.js
  src/components/users/new-user/new-user.component.js
  src/helpers/get-data.js
  src/services/agency.service.js
  src/services/user.service.js
Labels: enhancement

#66 #52 issue merge fix
  src/components/boardings/boarding-edit/boarding-edit.component.js
  src/components/boardings/boarding-edit/risks/risks.section.js
  src/components/boardings/boarding-edit/vessel/vessel.section.js
  src/services/boarding.service.js
Labels: bug

#67 Added ability to create agency
  src/components/agencies/agencies.component.js
  src/components/agencies/new-agency/new-agency.component.js
  src/components/agencies/new-agency/new-agency.css
  src/components/agencies/view-agency/view-agency.component.js
  src/components/users/new-user/new-user.component.js
Labels: enhancement

#69 Create user page redesign
  src/components/agencies/agencies.component.js
  src/components/users/new-user/new-user.component.js
  src/components/users/new-user/new-user.css
Labels: enhancement

#70 #32 Officer Image Uploader
  src/components/partials/photo-uploader/photo-uploader.component.js
  src/components/partials/photo-uploader/photo-uploader.css
  src/components/users/new-user/new-user.component.js
  src/services/stitch.service.js
Labels: enhancement

#71 #32 Officer Photo Upload
  src/components/users/edit-user/edit-user.component.js
  src/components/users/users.component.js
  src/helpers/get-data.js
  src/root/root.constants.js
  src/services/stitch.service.js
  src/services/user.service.js
Labels: enhancement

#81 Officer edit #15
  .gitignore
  src/components/boardings/boarding-edit/boarding-edit.component.js
  src/components/boardings/boarding-edit/risks/risks.section.js
  src/components/boardings/boarding-edit/vessel/vessel.section.js
  src/components/boardings/boarding-view/boarding-view.component.js
  src/components/partials/photo-uploader/photo-uploader.component.js
  src/components/partials/user-photo/user-photo.component.js
  src/components/partials/user-photo/user-photo.css
  src/components/users/edit-user/edit-user.component.js
  src/components/users/edit-user/edit-user.css
  src/components/users/new-user/new-user.component.js
  src/services/user.service.js
Labels: enhancement

#68 fix authentication
  src/components/auth/auth.component.js
  src/components/boardings/boarding-edit/boarding-edit.component.js
  src/components/header/profile/profile.component.js
  src/components/login/login.component.js
  src/helpers/localStorageData.js
  src/helpers/map-routing.js
  src/index.js
  src/root/root.component.js
  src/root/root.routes.js
  src/services/auth.service.js
Labels: enhancement

#84 Officer edit
  src/components/users/edit-user/edit-user.component.js
  src/components/users/edit-user/edit-user.css
  src/helpers/get-data.js
  src/services/user.service.js
Labels: enhancement

#86 Users subsystem fixes and merges
  src/components/boardings/boarding-edit/boarding-edit.component.js
  src/components/header/header.component.js
  src/components/partials/user-editor/user-editor.component.js
  src/components/partials/user-editor/user-editor.css
  src/components/profile/profile.component.js
  src/components/users/edit-user/edit-user.component.js
  src/components/users/new-user/new-user.component.js
  src/helpers/get-data.js
  src/root/root.component.js
  src/services/auth.service.js
Labels: bug

#92 Added photo to users table
  src/components/header/header.component.js
  src/components/partials/user-photo/user-photo.component.js
  src/components/users/users.component.js
Labels: enhancement

#93 Hash router integration
  src/components/login/login.component.js
  src/components/partials/custom-select/custom-select.js
  src/components/partials/search-panel/search-panel.component.js
  src/index.js
  src/root/root.history.js
  src/root/root.routes.js
Labels: bug, enhancement

#99 Location array
  src/components/boardings/boarding-edit/basic-info/basic-info.section.js
  src/components/boardings/boarding-view/basic-info/basic-info.section.js
  src/components/partials/user-editor/user-editor.component.js
  src/config.js
Labels: enhancement

#104 Date & Time filter for charts #83
  README.md
  src/components/boardings/boarding-view/crew/crew.section.js
  src/components/header/header.component.js
  src/components/home/boardings-section/boardings.section.js
  src/components/home/compliance-rate-section/compliance-rate.section.js
  src/components/home/home.component.js
  src/components/home/home.css
  src/components/home/patrol-hours-section/patrol-hours.section.js
  src/components/login/login.component.js
  src/components/partials/dates-range/dates-range.component.js
  src/components/partials/dates-range/dates-range.css
  src/components/partials/photo-uploader/photo-uploader.component.js
  src/components/partials/photo-uploader/photo-uploader.css
  src/components/partials/user-editor/user-editor.component.js
  src/components/partials/user-editor/user-editor.css
  src/components/partials/user-photo/user-photo.css
  src/components/profile/profile.component.js
  src/components/users/edit-user/edit-user.component.js
  src/components/users/edit-user/edit-user.css
  src/components/users/new-user/new-user.component.js
  src/helpers/i18n/en/translation.json
  src/helpers/map-routing.js
  src/index.js
  src/root/root.component.js
  src/root/root.css
  src/root/root.routes.js
  src/services/auth.service.js
  src/services/stitch.service.js
  src/styles/shared.css
Labels: enhancement
